version: 2
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
        environment:
          MULE_VERSION: 4.3.0
          MULE_APP_NAME: salesforce_integration
          MULE_ENV: Sandbox
          MULE_WORKER_TYPE: MICRO
          MULE_WORKER: 1
    steps:
      - checkout
      - restore_cache:
          key: 'dep-cache-{{ checksum "pom.xml" }}'
      - run: mvn clean packagr
      - save_cache:
          paths:
            - ~/target/repository
          key: 'dep-cache-{{ checksum "pom.xml" }}'
      - run:
          name: Build
          command: |
            mvn clean compile -s settings.xml
      - run: mkdir artifacts ; cp target/*.jar artifacts/application.jar
      - run:
          name: cloudhub deployment
          command: |
            mvn -s settings.xml clean deploy -DmuleDeploy\-DMULE_ENV=${MULE_ENV}\-DMULE_VERSION=${MULE_VERSION}\-DMULE_APP_NAME=${MULE_APP_NAME}\-DMULE_WORKER_TYPE=${MULE_WORKER_TYPE}\-DMULE_WORKER=${MULE_WORKER}\-DMULE_USERNAME=${MULE_USERNAME}\-Dcentral_password=${central_password}\-Dmule_repo_user=${mule_repo_user}\-Dmule_repo_pass=${mule_repo_pass}